### ISSUE TITLE
Error Object of class stdClass could not be converted to string

### ISSUE THREAD

**Issue by Thomasosho** [digikraaft/laravel-paystack-subscription#4]
```
// get transaction reference returned by Paystack
        $transactionRef = request()->input('reference');

        //verify the transaction is valid
        $transaction = Payment::hasValidTransaction($transactionRef);

            // create subscription for logged in user
                auth()->user()
                ->newSubscription('default', $transaction->data->plan)
                ->create($transaction->data->id);
```

**Comment by timoladoyinbo** [comment]
Hello @Thomasosho can you please provide a bit more context to where this error occurs?

**Comment by Thomasosho** [comment]
> Hello @Thomasosho can you please provide a bit more context to where this error occurs?

When a user tries subscribing, it registers the subscription on paystack, but then returns that error.
Plus i just recently started getting the error, it's been working fine until now.

**Comment by timoladoyinbo** [comment]
Thanks. I'll look into it and revert.

**Comment by Thomasosho** [comment]
from error log
````
[2021-04-14 21:49:52] local.ERROR: Object of class stdClass could not be converted to string {"userId":83,"exception":"[object] (Error(code: 0): Object of class stdClass could not be converted to string at /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Database/Connection.php:582)
[stacktrace]
#0 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Database/Connection.php(582): PDOStatement->bindValue(1, Object(stdClass), 2)
#1 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Database/Connection.php(487): Illuminate\\Database\\Connection->bindValues(Object(PDOStatement), Array)
#2 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('update `users` ...', Array)
#3 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\\Database\\Connection->runQueryCallback('update `users` ...', Array, Object(Closure))
#4 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Database/Connection.php(496): Illuminate\\Database\\Connection->run('update `users` ...', Array, Object(Closure))
#5 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Database/Connection.php(429): Illuminate\\Database\\Connection->affectingStatement('update `users` ...', Array)
#6 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2870): Illuminate\\Database\\Connection->update('update `users` ...', Array)
#7 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(801): Illuminate\\Database\\Query\\Builder->update(Array)
#8 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(808): Illuminate\\Database\\Eloquent\\Builder->update(Array)
#9 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(723): Illuminate\\Database\\Eloquent\\Model->performUpdate(Object(Illuminate\\Database\\Eloquent\\Builder))
#10 /home4/afiaprim/afiaprime/vendor/digikraaft/laravel-paystack-subscription/src/SubscriptionBuilder.php(95): Illuminate\\Database\\Eloquent\\Model->save()
#11 /home4/afiaprim/afiaprime/app/Http/Controllers/SubscriptionController.php(60): Digikraaft\\PaystackSubscription\\SubscriptionBuilder->create('1083789586', NULL, Array)
#12 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\SubscriptionController->handlePaystackPostCallBack()
#13 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('handlePaystackP...', Array)
#14 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\SubscriptionController), 'handlePaystackP...')
#15 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#16 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#17 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#28 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#35 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#36 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#37 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#38 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#39 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /home4/afiaprim/afiaprime/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /home4/afiaprim/afiaprime/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#54 /home4/afiaprim/afiaprime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#55 /home4/afiaprim/public_html/index.php(57): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#56 {main}
"} 
````

**Comment by Thomasosho** [comment]
from your documentation i noticed you talked about authorization codes
````
$user->newSubscription('default', 'PLN_paystackplan_code')->create(null, $authorizationCode);
````
so does it mean this will work?
````
auth()->user()
->newSubscription('default', $transaction->data->plan)
->create(null, $transaction->data->authorization->authorization_code);
````

I get this error when i try this
````
GuzzleHttp\Exception\ClientException
Client error: `POST https://api.paystack.co/subscription` resulted in a `400 Bad Request` response: { "status": false, "message": "This subscription is already in place." }
````

**Comment by timoladoyinbo** [comment]
Apologies for the late response, I  have not had time to look into this, I will do later today. From the last error you posted, it seems the subscription you're trying to create already exists hence the error: 

`Client error: POST https://api.paystack.co/subscription resulted in a 400 Bad Request response: { "status": false, "message": "This subscription is already in place." }`

When creating a subscription, you'll need the authorization code. This is usually from a successful transaction. If the authorization code has been previously used, Paystack would return the above error.

Once I take a closer look into it, I'll be able to identify what really the issue is and get back as soon as possible.

**Comment by Thomasosho** [comment]
I updated my `SubscriptionBuilder.php` file with this and it works. Because Paystack made some changes.

```
<?php


namespace Digikraaft\PaystackSubscription;

use Digikraaft\Paystack\Paystack;
use Digikraaft\Paystack\Subscription as PaystackSubscription;
use Digikraaft\Paystack\Transaction;
use Digikraaft\PaystackSubscription\Exceptions\PaymentFailure;
use Digikraaft\PaystackSubscription\Payment;
use Digikraaft\PaystackSubscription\Exceptions\SubscriptionUpdateFailure;

class SubscriptionBuilder
{

    /**
     * The model that is subscribing.
     *
     * @var \Illuminate\Database\Eloquent\Model
     */
    protected $owner;

    /**
     * The name of the subscription.
     *
     * @var string
     */
    protected string $name;

    /**
     * The ID or Code of the plan being subscribed to.
     *
     * @var string
     */
    protected string $plan;

    /**
     * The authorization code used to create subscription.
     *
     * @var string
     */
    protected string $authorization;

    /**
     * Create a new subscription builder instance.
     *
     * @param  mixed  $owner
     * @param  string  $name
     * @param  string  $plan
     * @return void
     */
    public function __construct($owner, $name, $plan)
    {
        $this->owner = $owner;
        $this->name = $name;
        $this->plan = $plan;
    }

    /**
     * Add a new Paystack subscription to the Paystack model.
     *
     * @param string|null $authorization
     * @param string $transactionId
     * @param array $customerOptions
     * @return \Digikraaft\PaystackSubscription\Subscription
     * @throws \Digikraaft\PaystackSubscription\Exceptions\PaymentFailure
     */
    public function add(string $transactionId = null, string $authorization = null, array $customerOptions = [])
    {
        return $this->create($transactionId, $authorization, $customerOptions);
    }

    /**
     * Create a new Paystack subscription.
     *
     * @param string|null $authorization
     * @param string|null $transactionId
     * @param array $customerOptions
     * @return \Digikraaft\PaystackSubscription\Subscription
     *
     * @throws Exceptions\PaymentFailure
     */
    public function create(string $transactionId = null, $authorization = null, array $customerOptions = [])
    {
        $customer = $this->getPaystackCustomer($customerOptions);

        if (is_null($authorization)) {
            $paystackSubscription = $this->createSubscriptionFromTransaction($transactionId, $customer);
        } else {
            $paystackSubscription = $this->createSubscriptionFromAuthorization($authorization, $customer);
            $this->authorization = $paystackSubscription->authorization;
        }
        
        $transactionRef = request()->input('reference');
        $transaction = Payment::hasValidTransaction($transactionRef);
        // save authorization to owner
        $this->owner->paystack_authorization = $paystackSubscription->most_recent_invoice->authorization;
        $this->owner->save();

        /** @var \Digikraaft\PaystackSubscription\Subscription $subscription */
        $subscription = Subscription::create([
            'name' => $this->name,
            'paystack_id' => $paystackSubscription->subscription_code,
            'paystack_status' => $paystackSubscription->status,
            'paystack_plan' => $transaction->data->plan,
            'quantity' => '1',
            'email_token' => $paystackSubscription->email_token,
            'authorization' => $this->authorization,
            'ends_at' => $paystackSubscription->next_payment_date,
            'user_id' => $this->owner->id,
        ]);

        return $subscription;
    }

    /**
     * Get the Paystack customer instance for the current user and payment method.
     *
     * @param  array  $options
     * @return \Digikraaft\Paystack\Customer
     */
    protected function getPaystackCustomer(array $options = [])
    {
        return $this->owner->createOrGetPaystackCustomer($options);
    }

    /**
     * Create a new Paystack subscription using authorization code.
     *
     * @param string|null $authorization
     * @param $customer
     * @return \Digikraaft\PaystackSubscription\Subscription
     */
    protected function createSubscriptionFromAuthorization(string $authorization, $customer)
    {
        $payload = array_merge(
            ['customer' => $customer->data->customer_code],
            ['authorization' => $authorization],
            ['plan' => $this->plan],
        );

        Paystack::setApiKey(config('paystacksubscription.secret', env('PAYSTACK_SECRET')));

        return PaystackSubscription::create(
            $payload,
        )->data;
    }

    /**
     * Create a new Paystack subscription using transaction reference.
     *
     * @param string $transactionId
     * @param $customer
     * @return \Digikraaft\PaystackSubscription\Subscription
     * @throws \Digikraaft\PaystackSubscription\Exceptions\PaymentFailure
     * @throws SubscriptionUpdateFailure
     */
    protected function createSubscriptionFromTransaction(string $transactionId, $customer)
    {
        //verify from Paystack that the transaction was successful
        Paystack::setApiKey(config('paystacksubscription.secret', env('PAYSTACK_SECRET')));
        $transaction = Transaction::fetch($transactionId);
        if (! $transaction->status || $transaction->data->status != 'success') {
            throw PaymentFailure::incompleteTransaction($transaction);
        }

        if ($transaction->data->plan->plan_code != $this->plan) {
            throw PaymentFailure::invalidTransactionPlan($transaction, $this->plan);
        }

        if ($transaction->data->customer->customer_code != $customer->data->customer_code) {
            throw SubscriptionUpdateFailure::invalidCustomer();
        }

        //check if user is already subscribed to plan. This is to guard against multiple subscriptions with the same transactionId
        if ($this->owner->subscribedToPlan($transaction->data->plan->plan_code)) {
            throw SubscriptionUpdateFailure::duplicateSubscription($this->owner, $transaction->data->plan->name);
        }

        $this->authorization = $transaction->data->authorization->authorization_code;

        $paystackSubscription = \Digikraaft\Paystack\Subscription::list(
            [
                'perPage' => 1,
                'page' => 1,
                'customer' => $transaction->data->customer->id,
                'plan' => $transaction->data->plan->id,
            ]
        );

        return $paystackSubscription->data->{0};
    }
}
```

**Comment by timoladoyinbo** [comment]
Hi @Thomasosho thanks for catching this. I also discovered the same thing and already have an update to be pushed tomorrow. Just looking into other areas if there are any new changes in paystack. Thanks.

**Comment by timoladoyinbo** [comment]
Hi @Thomasosho , I've pushed a new release that addresses this issue https://github.com/digikraaft/laravel-paystack-subscription/tree/v1.2.2
